### PR TITLE
Fix: Search Not Found

### LINKED ISSUE #72: [Frontend] explorer search not working
- can only search under this network or under all network?

### PR DESCRIPTION
**Pull request by kittybest**
- add network to search result
- but now can search under certain network, I think to search under many networks should be done after we can switch network on attester/user/epochkey page, and we have a page to show all the search results. 

close #72 .

### CODE REVIEW

**Comment by vivianjeng** [comment]
I think there is still some bug with the memory storage
e.g. if I perform
1. switch network to `sepolia`
2. search for `0xef0bb39d20480c0ea97611005027c8d72a82364c78b8b0ae362389ec7b15e61`
3. it works
4. switch network to `mumbai` (or any other network without the epoch key)
5. search for `0xef0bb39d20480c0ea97611005027c8d72a82364c78b8b0ae362389ec7b15e61`
6. it still shows the epoch key search result (and with network `mumbai`) but it is wrong
(you cannot find https://explorer-frontend-git-fix-search-unirep.vercel.app/mumbai/epochKey/0xef0bb39d20480c0ea97611005027c8d72a82364c78b8b0ae362389ec7b15e61 if you search directly)

**Comment by vivianjeng** [comment]
Sorry I revert the vercel settings in the main branch (and it is expired)
and also use the cloudflare config in this PR
https://github.com/Unirep/explorer/pull/77

could you rebase or reset the base to [b1f2877](https://github.com/Unirep/explorer/commit/b1f2877ca3f90e9b30e9a81c68acf3c7021655eb)
and commit the other 2 commits again 
thank you

**Comment by kittybest** [comment]
@vivianjeng rebase + fix all the bugs, please check 🙏

**Comment by vivianjeng** [comment]
we will not merge this [4fd7c51](https://github.com/Unirep/explorer/pull/75/commits/4fd7c519c81a22f436a55ad047f535e544e271ea)
but it is still in this PR if it is merged

can you reset the head to [ec80e89](https://github.com/Unirep/explorer/commit/ec80e899f243a6cc7ba7942242a7679d2f43d3df) (origin main)

**Comment by vivianjeng** [comment]
I reverted the vercel settings here
[637ead9](https://github.com/Unirep/explorer/pull/75/commits/637ead98cb77cb22f75877c48e0ad1404f1438d5)
please check @kittybest 

If it is okay we can merge this PR

**Pull request merged**
