### PR TITLE
Protocol info box

### PR DESCRIPTION
**Pull request by CJ-Rose**
was trying to tack this on to #17 but I was too slow

### CODE REVIEW

**Review by vimwitch — APPROVED** [review]
Make sure to rebase and force push before merging

**Comment by vimwitch** [comment]
Can do this with

```sh
git checkout main
git pull
git checkout protocol-info-box
git rebase main
git push -f
```

There shouldn't be any conflicts

**Comment by CJ-Rose** [comment]
um so it's all conflicts. Like it's asking me to resolve conflicts in 4-5 files through 8 stages.. looks like comparing current to changes in every commit you made to #17? This can't be the right way to handle this, for a PR that changes 2 lines and deletes a single block of code? Can I just close this one and make a new PR from a fresh branch off main?

**Comment by vimwitch** [comment]
Yea, another approach is

```sh
git checkout main
git branch -D potocol-info-box
git checkout -b protocol-info-box
git cherry-pick 4aa89364c91b7cc0d5bd9c91bc433eaea13d8f88
git push -fu origin protocol-info-box
```

**Comment by vimwitch** [comment]
not sure why it would all be conflicts, maybe it's trying to replay my commits onto the squashed commit

**Comment by CJ-Rose** [comment]
cool, that went smoothly, now I just merge it?

**Comment by vimwitch** [comment]
yep, you can squash or rebase to merge

**Pull request merged**
