### PR TITLE
Attester deployment data

### PR DESCRIPTION
**Pull request by CJ-Rose**

### CODE REVIEW

**Comment by CJ-Rose** [comment]
I'm trying to run `yarn prettier --someOption`, I'm just getting a list of options and "error Command failed with exit code 1"
what am I missing here?

**Comment by vimwitch** [comment]
Ah try running `yarn lint -w` in the root directory. I don't think we have a `prettier` package script defined.

**Comment by CJ-Rose** [comment]
ya that worked thx

**Comment by vimwitch** [comment]
I think this looks okay for now. We should track the number of attester/latest attester in the backend instead of returning all attesters though. For now it's fine but there could be lots of entries.

**Review by vimwitch — APPROVED** [review]

**Pull request merged**
